### ISSUE TITLE
Implement CLUBB-MF functionality on trunk: CLUBB externals

### ISSUE THREAD

**Issue by adamrher** [ESCOMP/CLUBB_CESM#4]
This issue is associated with the CPT to test / implement CLUBB-MF (MF = mass fluxes) into CAM, in coordination with JPL / UCLA & NCAR (@mikaelwitte, @JulioTBacmeister). For more information, please refer to the main issue at the cam repo here https://github.com/ESCOMP/CAM/issues/181.

The purpose of this issue is to get a primitive working version of CLUBB-MF onto the cam trunk ASAP. I am currently translating Mikaels CLUBB-MF code mods from an older tag to this more recent tag. I've forked / branch off of the latest CLUBB tag here: [clubb_release_b76a124.clubb-mf](https://github.com/adamrher/CLUBB_CESM/tree/clubb_release_b76a124.clubb-mf) which will contain all of the necessary code mods. I will respond to this thread when the code mods are ready to be merged.

**Comment by cacraigucar** [comment]
In the past, our version of CLUBB is a direct checkout of UWM's  CLUBB with one or two minor changes.  This is sounding like we might no longer be able to keep current with UWM's CLUBB repo without possible merge conflicts.  If that is the case, are there any plans to have this code ported into UWM's official code base?  

Perhaps I am mistaken about all of this, but I wanted to raise my concern if I'm not.

**Comment by adamrher** [comment]
I doubt Vince wants these changes in his code .... he seems a bit skeptical of this approach.

I am trying to make it as modular as possible to minimize merge conflicts with UWM. I have all the new subroutines in a separate module, and will just add a logical argument to the main CLUBB routine that activates the mass fluxes. Hopefully I can keep it to a handful of additional lines of code in the UWM code base, but perhaps I'm being too optimistic.

**Comment by mikaelwitte** [comment]
@adamrher, let's bring this point up in our CPT meeting today. Joao may want to contact Vince directly to discuss.

**Comment by cacraigucar** [comment]
Another thing to keep in mind, is that in the past the internal handling of variables within the CLUBB code changed dramatically.   That doesn't mean that something like that will happen in the future.  They have made dramatic changes to their internal code to which we've been isolated because they've maintained their interface with minor changes.  If you are linking to modules within their code, there is nothing that says that that module will exist in a future version.  The overhead of maintaining mods within CLUBB could make updating CLUBB  significantly more expensive for CAM.  Please keep this in mind as you move forward.

**Comment by adamrher** [comment]
Cheryl, thank you for this info. I'm making my best effort to avoid future merge catastrophes so this background is useful. I will focus on trying to keep all the code mods at the interface level when possible. I look forward to a rigorous code review with you!

**Comment by adamrher** [comment]
Closed issue after a mtg w/ Vince and Cheryl. Will instead attempt implement these mods on the CAM side.
